name: Unit Test (Push) & Builds

on: 
  push:
    branches-ignore:
      - 'docs'
    tags:
      - '*'
    paths:
      - 'src/**.js'
      - 'test/**.test.js'

  workflow_dispatch:
    inputs:
      test:
        description: 'Unit Tests'
      typings:
        description: 'Build Typings'
      docs:
        description: 'Build Documantation'

permissions: write-all

jobs:
  test:
    name: Unit Tests
    if: ${{ github.ref != 'refs/heads/main' || github.ref != 'refs/heads/develop' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node v16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      env:
        TMIO_API: ${{ secrets.TMIO_API }}
  
  typings:
    name: Build Typings
    after: test
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}

    steps:
    - name: Declare commit sha variables
      id: vars
      shell: bash
      run: echo "::set-output name=sha::$(echo ${GITHUB_SHA})"

    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Install Node v16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm
      
    - name: Install dependencies
      run: npm ci

    - name: Build d.ts files
      run: npm run dts
    
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m ":children_crossing: Build DefinitelyTyped - ${{ steps.vars.outputs.sha }}" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.gh_token }}
        branch: ${{ github.ref }}

  docs:
    name: Build Documentation
    after: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build and deploy documentation
        uses: discordjs/action-docs@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}