name: Publish

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod
  schedule:
    - cron: '0 0 */4 * *'
  release:
    types: [published]

jobs:
  publish-dev-npm:
    name: Publish Dev release on NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.event.inputs.release_type == 'dev' || github.event.schedule == '0 0 */4 * *'
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: 'develop'

      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Check previous released version
        id: pre-release
        run: |
          if [[ $(npm view trackmania.io@dev version | grep -e "$(jq --raw-output '.version' package.json)-dev.*.$(git rev-parse --short HEAD | cut -b1-3)") ]]; \
          then echo "release=false" >> "$GITHUB_OUTPUT"; \
          else echo "release=true" >> "$GITHUB_OUTPUT"; fi

      - name: Install dependencies
        if: steps.pre-release.outputs.release == 'true'
        run: npm ci --ignore-scripts

      - name: Deprecate old dev version
        if: steps.pre-release.outputs.release == 'true'
        run: "npm deprecate trackmania.io@$(npm view trackmania.io@dev version) 'no longer supported' || true"

      - name: Publish
        if: steps.pre-release.outputs.release == 'true'
        run: |
          npm version --git-tag-version=false $(jq --raw-output '.version' package.json)-dev.$(date +%d%m%y).$(git rev-parse --short HEAD)
          npm publish --tag dev || true


  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.event_name == 'release' || github.event.inputs.release_type == 'prod'
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci

      - name: Publish on NPM
        run: npm publish

  publish-ghp:
    name: Publish on Github Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: github.event_name == 'release' || github.event.inputs.release_type == 'prod'
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@GreepTheSheep'

      - name: Install dependencies
        run: npm ci

      - name: Set package scope for GitHub Packages
        run: |
          npm pkg set name="@GreepTheSheep/trackmania.io"
          npm pkg set publishConfig.registry="https://npm.pkg.github.com"

      - name: Publish on Github Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
