name: Publish on Release created

on:
  release:
    types: [created]

jobs:
  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Publish on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    name: Publish on Github Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@greepthesheep'

      - name: Install dependencies
        run: npm ci

      - name: Publish on Github Packages
        run: npm publish --registry=https://npm.pkg.github.com/@greepthesheep
        env:
          NODE_AUTH_TOKEN: ${{secrets.gh_token}}
