#This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release after PR to main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'package.json'
        prop_path: 'version'

      
      - name: Release
        id: create_release
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{steps.version.outputs.prop}} 
          release_name: Release ${{steps.version.outputs.prop}} 
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
