name: Release after PR to main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'version'
      - run: echo ${{steps.version.outputs.prop}}

      
      - name: Release
        id: create_release
        if: github.event.pull_request.merged
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.gh_token}}
        with:
          tag_name: v${{steps.version.outputs.prop}} 
          release_name: Release ${{steps.version.outputs.prop}} 
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
