name: Unit Tests (Pull Request)

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node v16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      env:
        TMIO_API: ${{ secrets.TMIO_API }}
