name: Unit Tests (Push)

on: 
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'src/**.js'
      - 'test/**.test.js'
  workflow_dispatch:

jobs:
  test:
    # check if the branch is not in a pull request
    if: ${{ github.event.pull_request != "opened" }}
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node v16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      env:
        TMIO_API: ${{ secrets.TMIO_API }}